services:
  react:
    image: node:18-alpine
    container_name: react
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./app
        target: /home/app
    working_dir: /home/app
    tty: true
